export const TOKEN_KEY = 'LOGIN/TOKEN_KEY'
export const CHECK_TOKEN_KEY = 'LOGIN/CHECK_TOKEN_KEY'
export const POST_LOGIN_DATA_REQUESTED = 'LOGIN/POST_LOGIN_DATA_REQUESTED'
export const POST_LOGIN_DATA_SUCCESSED = 'LOGIN/POST_LOGIN_DATA_SUCCESSED'
export const POST_LOGIN_DATA_FAILED = 'LOGIN/POST_LOGIN_DATA_FAILED'

export default {
    TOKEN_KEY,
    CHECK_TOKEN_KEY,
    POST_LOGIN_DATA_REQUESTED,
    POST_LOGIN_DATA_SUCCESSED,
    POST_LOGIN_DATA_FAILED,
}
