export const GET_HOME_DATA_REQUESTED = "home/GET_HOME_DATA_REQUESTED"
export const GET_HOME_DATA_SUCCESSED = "home/GET_HOME_DATA_SUCCESSED"
export const GET_HOME_DATA_FAILED = "home/GET_HOME_DATA_FAILED"

export default {
    GET_HOME_DATA_REQUESTED,
    GET_HOME_DATA_SUCCESSED,
    GET_HOME_DATA_FAILED,
}