export const GET_HOME_DATA_REQUESTED = 'HOME/GET_HOME_DATA_REQUESTED'
export const GET_HOME_DATA_SUCCESSED = 'HOME/GET_HOME_DATA_SUCCESSED'
export const GET_HOME_DATA_FAILED = 'HOME/GET_HOME_DATA_FAILED'

export default {
    GET_HOME_DATA_REQUESTED,
    GET_HOME_DATA_SUCCESSED,
    GET_HOME_DATA_FAILED,
}
