export const GET_USER_DATA_REQUESTED = 'USERS/GET_USER_DATA_REQUESTED'
export const GET_USER_DATA_SUCCESSED = 'USERS/GET_USER_DATA_SUCCESSED'
export const GET_USER_DATA_FAILED = 'USERS/GET_USER_DATA_FAILED'

export default {
    GET_USER_DATA_REQUESTED,
    GET_USER_DATA_SUCCESSED,
    GET_USER_DATA_FAILED,
}
